apiVersion: v1
kind: Service
metadata:
  name: ms-appointment-service
  namespace: pms
spec:
  selector:
    app: ms-appointment-service
  ports:
    - protocol: TCP
      port: 9083
      targetPort: 9083